### ISSUE TITLE
Some completed lessons

### ISSUE THREAD

**Issue by Lionstein** [Lionstein/ecommerce-pattern-library#2]
I've completed The Leftovers, from March 10th. My pages are built using the html and have been tested to make sure all the links are correct. All the config.yml pages are filled out.  

I've done Jekyll Generators on March 10th. The cards for the products page now work and are linked accordingly. 

I've done Homepage Template on March 17th. Each of the carousel images are linked with their specific product pages, and the homepage is built only with html, no css. 

I've done Finalizing Pattern Docs on March 17th. There is a README file with all the information, as well as screenshots for reference, and some notes about some weird nuances in my website. I believe it is formatted correctly and looked at some previous assignments README files, but if I missed anything I'll correct it immediately. 

The big thing missing is two pictures (one for carousel/cards and one for a specific product) because I am still in the process of building the Gundam needed for those pictures. The pictures will be done by this weekend.

Thank you! 
Kaitlyn Norquay

@@thomasjbradley

**Comment by thomasjbradley** [comment]
I’ve checked everything off except "Finalizing pattern docs".
Did you commit & push the README file?

**Comment by Lionstein** [comment]
Sorry! It's committed and pushed to Github now.

**Comment by thomasjbradley** [comment]
:white_check_mark:
