### ISSUE TITLE
Some completed lessons

### ISSUE THREAD

**Issue by Lionstein** [Lionstein/ecommerce-pattern-library#3]
I've completed Product List Page Template from Week 11. All products are listed across all 3 individual product pages (the three are basically basic-moderate-best quality products) and the final product image is in place. All buttons lead to their respective product details page. 

I've completed Product Details Page Template from Week 12. The 4 individual product details pages have their corresponding pictures and information filled out. They're made accessible from the product list pages and the homepage carousel. 

Let me know if there's any issues, see you on Tuesday!
Kaitlyn Norquay

@thomasjbradley

**Comment by thomasjbradley** [comment]
🤖
