### ISSUE TITLE
Edge Browser Testing

### ISSUE THREAD

**Issue by CedricRobitaille** [Lionstein/ecommerce-pattern-library#4]
@thomasjbradley

After the 4 (working) banner slides, there is a 5th blank image. (see below).

Other than that, all's good.

![kat-1](https://user-images.githubusercontent.com/29230560/79262995-2327ea00-7e60-11ea-9d79-c48dd77c9143.PNG)

**Comment by Lionstein** [comment]
Issues with animated carousel:
In Edge, blank page appears after clicking on radio buttons
In Edge (on my computer) clicking on radio buttons stops animation altogether
In Chrome (on my computer) clicking a previous radio button will stop animation, but clicking the next radio button after will turn the animation back on. Blank slide also appears, but is irregular
